spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/smore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://smore-dev-mysql.c7cca4g8ujfq.ap-northeast-2.rds.amazonaws.com:3306/smore
    username: root
    password: "00001234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
#      uri: "mongodb://root:00001234@127.0.0.1:27017/smore?tls=true&tlsAllowInvalidHostnames=true&authMechanism=SCRAM-SHA-1&retryWrites=false"
      uri: "mongodb://root:00001234@127.0.0.1:27017/smore_chat_db?authSource=admin"
  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update