spring:
  datasource:
    #    url: jdbc:mysql://127.0.0.1:3306/smore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://smore-dev-rds-instance.c7cca4g8ujfq.ap-northeast-2.rds.amazonaws.com:3306/smore
#    url: jdbc:mysql://127.0.0.1:3306/smore
    username: root
    password: "00001234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      #      uri: "mongodb://root:00001234@127.0.0.1:27017/smore?tls=true&tlsAllowInvalidHostnames=true&authMechanism=SCRAM-SHA-1&retryWrites=false"
      uri: "mongodb://root:00001234@127.0.0.1:27017/smore_chat_db?authSource=admin"
    redis:
      host: localhost
      port: 6379
  docker:
    compose:
      enabled: false
  elasticsearch:
    restclient:
      ssl:
        enabled: true
        verification-mode: none
      uris:  https://a525-221-149-72-194.ngrok-free.app
      headers:
        ngrok-skip-browser-warning: "any-value"

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
          jpa: DEBUG
        elasticsearch:
          restclient: DEBUG
          rest: DEBUG
      elasticsearch:
        client: DEBUG
custom:
  elasticsearch:
    uri: https://a525-221-149-72-194.ngrok-free.app
