spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/smore?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://127.0.0.1:3306/smore
    username: root
    password: "00001234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
#      uri: "mongodb://root:00001234@127.0.0.1:27017/smore?tls=true&tlsAllowInvalidHostnames=true&authMechanism=SCRAM-SHA-1&retryWrites=false"
      uri: "mongodb://root:00001234@127.0.0.1:27017/smore_chat_db?authSource=admin"
  docker:
    compose:
      enabled: false
  elasticsearch:
    restclient:
      uris: http://localhost:9200
      # 필요한 경우 타임아웃이나 인증 정보도 추가할 수 있습니다.
      # connection-timeout: 5000
      # read-timeout: 60000
    rest:
      uris: http://localhost:9200
      # 필요한 경우 타임아웃이나 인증 정보도 추가할 수 있습니다.
      # connection-timeout: 5000
      # read-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
        data:
          elasticsearch: DEBUG
          jpa: DEBUG
custom:
  elasticsearch:
    uri: http://localhost:9200